import Head from 'next/head'
import Grid from './components/Grid'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {
    const res = await fetch(`https://api.opendota.com/api/heroes`)
    const data = await res.json();

    return { props: { data } }
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Dota Dossiers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewporSt" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data &&
        <main className={styles.main}>
          <Grid data={data} />
        </main>
      }
    </>
  )
}
